import assert from "node:assert/strict";
import { test } from "node:test";
import { END, injectBlock, START } from "../src/inject.mjs";

test("replaces only the text between the markers", () => {
  const before = `# Title\n\nIntro.\n\n${START}\nold map\n${END}\n\n## After\n`;
  const after = injectBlock(before, "NEW MAP\n");
  assert.ok(after.startsWith(`# Title\n\nIntro.\n\n${START}\n`));
  assert.ok(after.endsWith(`\nNEW MAP\n${END}\n\n## After\n`));
  assert.ok(!after.includes("old map"));
  assert.ok(after.includes("Generated by codemap"));
});

test("is idempotent", () => {
  const once = injectBlock(`${START}\n${END}\n`, "MAP");
  assert.equal(injectBlock(once, "MAP"), once);
});

test("keeps CRLF line endings", () => {
  const after = injectBlock(`a\r\n${START}\r\n${END}\r\nb\r\n`, "line1\nline2\n");
  assert.ok(!/[^\r]\n/.test(after), "no bare LF introduced");
  assert.ok(after.includes("line1\r\nline2"));
});

test("refuses to guess when markers are missing, duplicated or reversed", () => {
  assert.throws(() => injectBlock("# no markers\n", "x"), /markers not found/);
  assert.throws(() => injectBlock(`${START}\n${END}\n${START}\n${END}\n`, "x"), /more than once/);
  assert.throws(() => injectBlock(`${END}\n${START}`, "x"), /comes before/);
});

test("markers inside code fences or mid-line are ignored", () => {
  const doc = [
    "Usage:",
    "```markdown",
    START,
    END,
    "```",
    "~~~",
    START,
    "~~~",
    `Inline mention of ${START} is not a marker.`,
    "",
    START,
    "old",
    END,
    "",
  ].join("\n");
  const after = injectBlock(doc, "MAP");
  assert.ok(after.startsWith(["Usage:", "```markdown", START, END, "```"].join("\n")), "example untouched");
  assert.ok(after.includes(`${START}\n<!-- Generated`) && after.includes(`MAP\n${END}\n`));
  assert.ok(!after.includes("old"));
  assert.equal(injectBlock(after, "MAP"), after, "idempotent");
});

test("indented marker lines count", () => {
  assert.ok(injectBlock(`  ${START}\n  ${END}\n`, "MAP").includes("MAP"));
});
