// Replaces the text between the codemap markers in a Markdown file, leaving
// everything else byte-for-byte untouched. Pure: text in, text out.
//
//   <!-- codemap:start -->
//   ...generated, overwritten on every run...
//   <!-- codemap:end -->
//
// A marker counts only when it is alone on its line and outside a fenced
// code block, so a README can show the markers as a usage example (this
// tool's own README does). Missing, duplicated or reversed markers are
// errors: guessing where to put the map would risk overwriting hand-written
// README text.

export const START = "<!-- codemap:start -->";
export const END = "<!-- codemap:end -->";
const NOTICE = "<!-- Generated by codemap. Edit codemap.config.json and re-run; changes here are overwritten. -->";

export function injectBlock(text, block) {
  const { starts, ends } = findMarkers(text);
  if (starts.length === 0 || ends.length === 0) {
    throw new Error(`markers not found — add these two lines where the map should go:\n  ${START}\n  ${END}`);
  }
  if (starts.length > 1 || ends.length > 1) throw new Error("codemap markers appear more than once");
  const [s] = starts; // offset of the start line's first character
  const [e] = ends;
  if (e < s) throw new Error(`"${END}" comes before "${START}"`);

  // Keep the file's own line endings (a Windows checkout may be CRLF).
  const eol = text.includes("\r\n") ? "\r\n" : "\n";
  const body = `${NOTICE}\n\n${block.trim()}`.replace(/\r?\n/g, eol);
  const startLineEnd = s + text.slice(s).indexOf(START) + START.length;
  const endLineStart = e + text.slice(e).indexOf(END);
  return text.slice(0, startLineEnd) + eol + body + eol + text.slice(endLineStart);
}

// Offsets of marker lines outside ``` / ~~~ fences (CommonMark: a fence
// closes with the same character, at least as long as the opener).
function findMarkers(text) {
  const starts = [];
  const ends = [];
  let fence = null;
  let offset = 0;
  for (const line of text.split("\n")) {
    const trimmed = line.replace(/\r$/, "").trim();
    const f = trimmed.match(/^(`{3,}|~{3,})/);
    if (fence) {
      if (f && f[1][0] === fence[0] && f[1].length >= fence.length && trimmed === f[1]) fence = null;
    } else if (f) {
      fence = f[1];
    } else if (trimmed === START) {
      starts.push(offset);
    } else if (trimmed === END) {
      ends.push(offset);
    }
    offset += line.length + 1;
  }
  return { starts, ends };
}
